services:
  agileDemo-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: agile-demo-app:latest
    container_name: agileDemo-app
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - agileDemo-mysql
    environment:
      DB_HOST: agileDemo-mysql
      DB_USER: user99
      DB_PASSWORD: user99
      DB_NAME: comp7780
    mem_limit: 256m
    cpus: '0.6'

  agileDemo-mysql:
    image: mysql:8
    container_name: agileDemo-mysql
    # command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: comp7780
      MYSQL_USER: user99
      MYSQL_PASSWORD: user99
    volumes:
      - agileDemo_mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    command: >
      bash -c "
      rm -rf /var/lib/mysql/* &&
      docker-entrypoint.sh mysqld --innodb-buffer-pool-size=128M
      "
    mem_limit: 512m
    cpus: '0.8'
volumes:
  agileDemo_mysql_data: