services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: user99
      DB_PASSWORD: user99
      DB_NAME: comp7780

  mysql:
    image: mysql:8
    # command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: comp7780
      MYSQL_USER: user99
      MYSQL_PASSWORD: user99
    volumes:
      - ./mysql_scripts:/docker-entrypoint-initdb.d
